language: node_js
node_js: 10
cache: yarn
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition: '"$TRAVIS_JOB_NUMBER" == *.1'
script:
  - yarn run lint
  - yarn test -- -- --ci --coverage
  - 'if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then yarn build:storybook; fi'
after_success:
  - bash <(curl -s https://codecov.io/bash)
